name: Compile

on:
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sm-version: [ '1.11.x', '1.12.x']
    
    steps:
      - name: Install Checkout
        uses: actions/checkout@v1
      
      - name: Install Setup SP ${{ matrix.sm-version }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.sm-version }}
      
      - name: Install Misc
        run: bash scripts/setup.sh
        working-directory: ./
      
      - name: Minimum Compile ${{ matrix.sm-version }}
        run: bash compile.sh
        working-directory: ${{ env.SCRIPTS_PATH }}
      
      - name: Install Optional Includes
        run: bash scripts/optional.sh
        working-directory: ./
      
      - name: Full Compile ${{ matrix.sm-version }}
        run: bash compile.sh
        working-directory: ${{ env.SCRIPTS_PATH }}
